#!/bin/bash
#
# chkconfig: 35 90 12
# description: launch ipfs daemon
# process name: ipfs

# Get function from functions library
. /etc/rc.d/init.d/functions

IPFS="/usr/local/bin/ipfs"
RETVAL=0

getpid() {
    pid=`ps -eo pid,command | grep ipfs | grep -v grep | awk '{ print $1 }'`
}

# Start the service testrpc
start() {
        echo -n $"Starting IPFS server: "
	getpid
	if [ -z "$pid" ]; then
		$IPFS init
		$IPFS daemon > /dev/null &
		RETVAL=$?
	fi
	if [ $RETVAL -eq 0 ]; then
		touch /var/lock/subsys/ipfs
		echo_success
	else
		echo_failure
	fi
	echo
	return $RETVAL
}

# Stop the service testrpc
stop() {
	echo -n $"Stopping IPFS: "
	getpid
	RETVAL=$?
	if [ -n "$pid" ]; then
		kill -HUP $pid
		sleep 1
		getpid
		if [ -z "$pid" ]; then
			rm -f /var/lock/subsys/ipfs
			echo_success
		else
			echo_failure
		fi
	else
		echo -n $"IPFS already Stopped."
		echo_failure
	fi
	echo
	return $RETVAL
}

### main logic ###
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        getpid
	    if [ -n "$pid" ]; then
            echo "IPFS (pid $pid) is running."
        else
            RETVAL=1
            echo "IPFS is stopped"
        fi
        ;;
  restart|reload|condrestart)
        stop
        start
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|reload|status}"
        exit 1
esac

exit $RETVAL
